module.exports = {
  NO_RESULT: {code: 'NO_RESULT', message: 'No Resultset'},
  INVAILD_TOKEN: {code: 'INVAILD_TOKEN', message: ''},
  MISSING_PARAMETER: {code: 'MISSING_PARAMETER', message: ''},
  DB_CONNECTION: {code: 'DB_CONNECTION', message: ''},
  QUERY_FAIL: {code: 'QUERY_FAIL', message: ''},
  SEND_MAIL_FAIL: {code: 'SEND_MAIL_FAIL', message: 'Mailer Error'},
  INSUFFICIENT_DATA: {code: 'INSUFFICIENT_DATA', message: 'Check your Request information'},
  UNEXPECTED_CODE: {code: 'UNEXPECTED_CODE', message: 'There is no return code'},
  AUTH_FAIL_NULL: {code: 'AUTH_FAIL_NULL', message: 'Email and Password must be filled out'},
  AUTH_FAIL_INVALID_EMAIL: {code: 'AUTH_FAIL_INVALID_EMAIL', message: 'Check your Request information'},
  AUTH_FAIL_INVALID_PW: {code: 'AUTH_FAIL_INVALID_PW', message: 'Check your Request information'},
  AUTH_FAIL_EMAIL_NOT_EXIST: {code: 'AUTH_FAIL_EMAIL_NOT_EXIST', message: 'Check your Request information'},
  AUTH_FAIL_NOT_MATCH: {code: 'AUTH_FAIL_NOT_MATCH', message: 'Check your Request information'},
  AUTH_FAIL_DELETED: {code: 'AUTH_FAIL_NOT_MATCH', message: 'This account has been deleted'},
  AUTH_FAIL_SUSPENDED: {code: 'AUTH_FAIL_NOT_MATCH', message: 'This account has been suspended'},
  AUTH_FAIL_NOT_MAIN_ACCOUNT: {code: 'AUTH_FAIL_NOT_MAIN_ACCOUNT', message: 'sub accounts are not accessible'},
  SIGNUP_FAIL_NULL: {code: 'SIGNUP_FAIL_NULL', message: 'Email and Password must be filled out'},
  SIGNUP_FAIL_INVALID_EMAIL: {code: 'SIGNUP_FAIL_INVALID_EMAIL', message: 'Check your Request information'},
  SIGNUP_FAIL_INVALID_PW: {code: 'SIGNUP_FAIL_INVALID_PW', message: 'Check your Request information'},
  SIGNUP_FAIL_TRANSACTION: {code: 'SIGNUP_FAIL_TRANSACTION', message: ''},
  SIGNUP_FAIL_EMAIL_EXIST: {code: 'SIGNUP_FAIL_EMAIL_EXIST', message: ''},
  ACCESS_TOKEN_EMPTY: {code: 'ACCESS_TOKEN_EMPTY', message: 'Check your Request information'},
  ACCESS_TOKEN_EXPIRED: {code: 'ACCESS_TOKEN_EXPIRED', message: 'Check your Request information'},
  ACCESS_TOKEN_INVALID: {code: 'ACCESS_TOKEN_INVALID', message: 'Check your Request information'},
  AUTH_FAIL_AID_NOT_EXIST: {code: 'AUTH_FAIL_AID_NOT_EXIST', message: 'Check your Request information'},
  AID_NOT_EXIST: {code: 'AID_NOT_EXIST', message: 'Check your Request information'},
  AUTH_FAIL_PARENT_AID_NOT_MATCH: {code: 'AUTH_FAIL_PARENT_AID_NOT_MATCH', message: 'Check your Request information'},
  REFRESH_TOKEN_INVALID: {code: 'REFRESH_TOKEN_INVALID', message: 'Check your Request information'},
  AUTH_FAIL_TOKEN_NULL: {code: 'AUTH_FAIL_TOKEN_NULL', message: 'Check your Request information'},
  AUTH_FAIL_RESTRICT: {code: 'AUTH_FAIL_RESTRICT', message: ''},
  FAIL_TRANSACTION: {code: 'FAIL_TRANSACTION', message: ''},
  FAIL_EMAIL_EXIST: {code: 'FAIL_EMAIL_EXIST', message: ''},
  FAIL_ALREADY_CONFIRM: {code: 'FAIL_ALREADY_CONFIRM', message: ''},
  FAIL_NOT_EXIST: {code: 'FAIL_NOT_EXIST', message: ''},
  NOT_MATCH: {code: 'NOT_MATCH', message: ''},
  NOT_EXIST: {code: 'NOT_EXIST', message: ''},
  HAS_META: {code: 'HAS_META', message: ''},
  NOT_ENOUGH: {code: 'NOT_ENOUGH', message: ''},

}